Sunbird-Ed/sunbird-data-products

scripts/ecg_learning.py

This shows TPS across a week. It is updated on an hourly basis. This graph will be configured in the dashboard page of MHRD. The data for the Graph will be taken from Prometheus DB by using API.

#SB-15205 | L1 Version of MHRD, PMO, CM Dashboards - ECG of Learning | updating the script for run for 7 days by argument

---

resources/queries/content_list.json
src/main/python/dataproducts/consumption/consumption_metrics.py
src/main/python/dataproducts/consumption/consumption_metrics_last_30_days.py
src/main/python/dataproducts/consumption/content_consumption.py
src/main/python/dataproducts/consumption/ecg_learning.py
src/main/python/dataproducts/etb/ETB_creation_metrics.py
src/main/python/dataproducts/etb/content_creation.py
src/main/python/dataproducts/etb/content_progress.py
src/main/python/dataproducts/location/district_monthly.py
src/main/python/dataproducts/location/district_weekly.py
src/main/python/dataproducts/tpd/course_consumption.py
src/main/python/dataproducts/tpd/course_enrolments.py
src/main/python/util/utils.py

Fixed the below-mentioned issues.
1. Author name for all contents is showing "Unknown", though it is actually present (can see it in content details page)
2. For many contents, the Board, Medium, Grade, Subject values are shown as "Unknown", although the content details page shows the details.
3. All assets and textbooks are also present in the report.

#SB-15945 | Content consumption report issue fixes

---

resources/queries/district_devices.json
resources/queries/district_devices_monthly.json
resources/queries/district_plays.json
resources/queries/district_scans.json
src/main/python/dataproducts/location/district_monthly.py
src/main/python/dataproducts/location/district_weekly.py

Changes added for district level reports to use **derived location details** from Druid.
The changes have been added for following reports:
1. District Level Monthly Devices
2. District-wise Weekly Usage Report

Location details updates to district level reports

---

resources/queries/content_list.json
resources/queries/district_devices.json
resources/queries/district_devices_monthly.json
resources/queries/district_plays.json
resources/queries/district_scans.json
src/main/python/dataproducts/consumption/content_consumption.py
src/main/python/dataproducts/location/district_monthly.py
src/main/python/dataproducts/location/district_weekly.py

The following fixes are added to the content consumption report.
1. Add only Creator (User Name) field
2. The plays, playtime fields should not have Unknown but 0 instead
3. Remove total ratings and Average rating should be there
4. Last date of the week, should always be the date on which the report is fetched
5. Assessmentitem's are removed from report.

Content consumption report fixes for author and field value as unknown

---

requirements.txt
resources/queries/content_list.json
src/main/python/dataproducts/consumption/content_consumption.py
src/main/python/dataproducts/location/district_monthly.py
src/main/python/dataproducts/location/district_weekly.py
src/main/python/util/kafka_utils.py
src/main/python/util/utils.py

Fixes for Blank entries in District in the district level weekly report is been added

#SB-16205 | Fixes for Blank entries in District

---

Jenkinsfile
build.sh

@SanthoshVasabhaktula : Jenkinsfile is been added for artifact creation on the deployment. Please review it.

Adding Jenkinsfile for artifact creation

---

build.py
src/main/python/dataproducts/services/location/district_monthly.py
src/main/python/dataproducts/services/location/district_weekly.py
src/main/python/dataproducts/util/utils.py
src/main/scripts/dataproducts

#SB-15589 | Location verification added District level report

---

python-scripts/src/main/python/dataproducts/services/location/user_detail_report.py
python-scripts/src/main/python/dataproducts/util/utils.py

Including state user files in the districts wise csv files zip added   | #SB-17501

---

build.py
src/main/python/dataproducts/services/location/user_detail_report.py

#SB-17790 | User detail report file name changes

---

python-scripts/Jenkinsfile
python-scripts/src/main/python/dataproducts/resources/queries/content_list.py
python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py

@SanthoshVasabhaktula : Following Changes are added in this PR.
1. Jenkinsfile changes for the updated folder structure
2. Aggregated Content Consumption Report
Please review it

#SB-17458 | Aggregated Content Consumption Report

---

data-products/src/main/scala/org/sunbird/analytics/job/report/StateAdminReportJob.scala

In user_detail.csv the column ClaimStatus is shown with status as (1,2,3..6), now it is changed readable form as ("claimed", "unclaimed")

Issue #SB-17937 changing user status to readable form in user_detail.csv

---

python-scripts/build.py

@SanthoshVasabhaktula : Build version is updated. Please review it.

#SB-18043 | Build version updated

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py
python-scripts/src/main/scripts/dataproducts

#SB-17458 | Textbook detail is added for contents

---

python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py
python-scripts/src/main/python/dataproducts/util/utils.py
python-scripts/src/main/scripts/dataproducts

@SanthoshVasabhaktula : please review it.

#SB-17946 | Changes to weekly content consumption report is added

---

python-scripts/src/main/python/dataproducts/resources/queries/content_list.py
python-scripts/src/main/python/dataproducts/services/etb/content_creation_status.py
python-scripts/src/main/python/dataproducts/services/location/user_detail_report.py
python-scripts/src/main/python/dataproducts/util/utils.py
python-scripts/src/main/scripts/dataproducts

In this PR the following things are added.
1. Content Creation Status Report
2. Changes added for updated folder structure user detail report
@SanthoshVasabhaktula :  Please review it.

#SB-16763 | Content creation report and user detail report changes added

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/resources/queries/content_plays.py
python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py
python-scripts/src/main/python/dataproducts/util/utils.py

Content consumption report's name changes and content play query fixes added 

---

data-products/src/main/scala/org/sunbird/analytics/job/report/StateAdminReportJob.scala

Faced issues while finding whether is report is actually running or not.
This help in finding all the necessary files were generated while running this report.

Issue #SB-17937 added logs for StateAdminReport

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/resources/queries/content_list.py
python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py

@SanthoshVasabhaktula : Please review it

#SB-17458 | Field name fixes are added Content consumption report

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/resources/queries/content_list.py
python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py

@SanthoshVasabhaktula : please review it.

Content consumption report query fixes are added

---

python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py

Fixes of average timespent in Content Consumption report

---

python-scripts/requirements.txt
python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py
python-scripts/src/main/python/dataproducts/services/consumption/report_merger.py

@SanthoshVasabhaktula : please review it.

Report merger config with container

---

data-products/src/main/scala/org/sunbird/analytics/job/report/StateAdminReportJob.scala
data-products/src/test/scala/org/sunbird/analytics/job/report/TestStateAdminReportJob.scala

Reverts Sunbird-Ed/sunbird-data-products#69

Revert "SC 1746 - segregating user-details based on the claim status(changes done for 2.10)"

---

data-products/src/main/scala/org/sunbird/analytics/model/report/TextbookProgressModel.scala

Fixes:
- Textbook Progress Model generating for lesser tenants.
- Added missing field 'Total Content' in aggregated report.

Fixes for Textbook Progress Model generating for lesser tenants

---

python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py
python-scripts/src/main/scripts/dataproducts

Issue #SB-19214 fix: read from correct druid rollup source

Content Consumption correct Druid rollup read

---

python-scripts/src/main/scripts/dataproducts

Content consumption

---

data-products/src/main/scala/org/sunbird/analytics/job/report/AssessmentMetricsJob.scala
data-products/src/main/scala/org/sunbird/analytics/job/report/CourseMetricsJob.scala
data-products/src/main/scala/org/sunbird/analytics/util/ESUtil.scala
data-products/src/test/scala/org/sunbird/analytics/job/report/TestAssessmentMetricsJob.scala

Benchmark and optimization result report link: https://docs.google.com/spreadsheets/d/14hqsnidYJPejpTM6ka4sXjkxryxIvoVeHgaWbb-6E_c/edit?usp=sharing
analytics core: project-sunbird/sunbird-analytics-core#29

Report dataproducts job optimisation

---

data-products/src/test/scala/org/sunbird/analytics/model/report/TestCourseEnrollmentModel.scala
python-scripts/src/main/python/dataproducts/services/consumption/report_merger.py

Config update for report container added

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/consumption/report_merger.py

@RevathiKotla : Please review it

Issue #000 | Date format config added

---

python-scripts/src/main/python/dataproducts/services/consumption/report_merger.py

@RevathiKotla : Please review it.

Column order fixes added in report merger

---

data-products/src/main/scala/org/sunbird/analytics/job/report/StateAdminReportJob.scala

Trying to remove invalid data in test environments.

SH-237  filtering originalchannel column in usr_external table to notnull

---

data-products/src/main/resources/application.conf
data-products/src/main/scala/org/sunbird/analytics/job/report/StateAdminReportJob.scala
data-products/src/main/scala/org/sunbird/analytics/util/DecryptUtil.scala

Changed logs level to info
Removed sunbird_encryption_key value from application.conf
Printed encryption-key length in order to identify the value is copying or not

SH-691 added info logs

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/consumption/landing_page.py
python-scripts/src/main/python/dataproducts/util/azure_utils.py
python-scripts/src/main/python/dataproducts/util/utils.py

@SanthoshVasabhaktula : Please review it

#SB-19583 | Private and Public container implementation added

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/consumption/landing_page.py
python-scripts/src/main/python/dataproducts/util/utils.py

@SanthoshVasabhaktula : Please review it

#SB-19583 | Private & public container name changes added

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/consumption/report_merger.py
python-scripts/src/main/python/dataproducts/util/utils.py

@sowmya-dixit : Please review it.

Issue #SB-19583 | public container fixes added

---

adhoc-scripts/src/main/scala/UserOrgDataMigration.scala

user org data migration script.

Issue #TG-462 feat:user org migration script

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/consumption/content_consumption.py
python-scripts/src/main/python/dataproducts/util/utils.py

@sowmya-dixit : Please review it.

Issue #000 | mimetype fixes added

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/location/user_declaration_report.py
python-scripts/src/main/python/dataproducts/services/location/user_detail_report.py
python-scripts/src/main/python/dataproducts/util/azure_utils.py
python-scripts/src/main/python/dataproducts/util/utils.py
python-scripts/src/main/scripts/dataproducts

@SanthoshVasabhaktula : Please review it

Issue #00 | Public container fixes added for Azure utils

---

data-products/src/main/scala/org/sunbird/analytics/job/report/StateAdminReportJob.scala

Due to latest code changes while decrypting the report for email and phone values, the values are seen from wrong columns.

SH-1056 email and phone column value got misplaced in the reports.

---

etl-jobs/src/main/scala/org/sunbird/analytics/jobs/UserCacheIndexer.scala

1. user_org name changed to user_organisation
2. For custodian user -> user_declaration table introduced

Migration script changes for table name changes

---

data-products/src/main/resources/application.conf
data-products/src/main/scala/org/sunbird/analytics/exhaust/OnDemandExhaustJob.scala
data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/BaseCollectionExhaustJob.scala
data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/ResponseExhaustJob.scala
data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/UserInfoExhaustJob.scala

- Update the user info exhaust with new consent rules
- Refactor a bit
- Complete testing on ondemand flows

Issue #000 feat: Generic collection exhausts

---

data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/BaseCollectionExhaustJob.scala

Updating the `dt_job_completed ` col when the report is got success

Report job fix

---

python-scripts/build.py
python-scripts/src/main/python/dataproducts/services/consumption/landing_page.py
python-scripts/src/main/python/dataproducts/services/consumption/report_merger.py
python-scripts/src/main/python/dataproducts/util/azure_utils.py
python-scripts/src/main/python/dataproducts/util/utils.py
python-scripts/src/main/scripts/dataproducts

@sowmya-dixit : Please review it

Private and public container isolation for reports added

---

python-scripts/src/main/python/dataproducts/services/location/user_declaration_report.py

Reverts Sunbird-Ed/sunbird-data-products#253

Revert "Issue #SC-2050 fix: handle data parse error inside try-catch; optimiz…"

---

data-products/src/main/scala/org/sunbird/analytics/job/report/CollectionSummaryJob.scala

Computing the completion count by "completedon" col

Collection Summary data-product update

---

data-products/src/main/scala/org/sunbird/analytics/exhaust/OnDemandExhaustJob.scala
data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/BaseCollectionExhaustJob.scala
data-products/src/main/scala/org/sunbird/analytics/exhaust/collection/UserInfoExhaustJob.scala

1. Accept requests with batchFilter
2. Class cast exception fix for Long.
3. blob upload - exception handling.

DIK-4147 - Fixes

---

data-products/src/main/scala/org/sunbird/analytics/audit/CourseBatchStatusUpdaterJob.scala

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please choose appropriate options.
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Software versions:
* Hardware versions:

SB-24096  Adding missing "enddate" filed into course metadata.

---

data-products/src/main/scala/org/sunbird/analytics/audit/CourseBatchStatusUpdaterJob.scala

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please choose appropriate options.
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Software versions:
* Hardware versions:

SB-24096  Adding name filed into course metadata.

---

data-products/src/main/scala/org/sunbird/analytics/audit/CollectionReconciliationJob.scala
data-products/src/main/scala/org/sunbird/analytics/job/report/CollectionSummaryJobV2.scala

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24151" title="SB-24151" target="_blank"><img alt="Sub-task" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10316&avatarType=issuetype" />SB-24151</a>  DataProduct changes to handle the date columns
</td></table>
<br />
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please choose appropriate options.
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Software versions:
* Hardware versions:

#SB-24151: Data product issue fixes added for Date Field changes

---

etl-jobs/build.Jenkinsfile

fix: typo in jenkinsfile - SB-24494
